name: azure_app_config
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  intl: ^0.17.0
  clock: ^1.1.1
  shared_preferences: ^2.0.15
  connection_string_parser: ^1.0.1
  
dev_dependencies:
  test: ^1.21.6

