name: azure_app_config
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  intl: ^0.17.0
  clock: ^1.1.1
  
dev_dependencies:
  test: ^1.21.6
  http_mock_adapter: ^0.3.3
  mocktail: ^0.3.0

