name: azure_app_config
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  freezed: ^2.2.0
  json_annotation: ^4.7.0
  
dev_dependencies:
  test: ^1.21.6
  http_mock_adapter: ^0.3.3
  mockito: ^5.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
