name: azure_remote_config
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  crypto: ^3.0.2
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  intl: ^0.17.0
  json_annotation: ^4.4.0

dev_dependencies:
  json_serializable: ^6.0.0
  build_runner: ^2.2.1
